# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/release.yml on each tagged release.
# Source template: tools/homebrew/lore.cask.rb in AoJ/lore. Do not hand-edit
# in the tap — edit the template instead.

cask "lore" do
  version "@@VERSION@@"
  sha256 "@@SHA_APP@@"

  # Public repo → plain release-asset URL, no token/strategy needed.
  url "https://github.com/AoJ/lore/releases/download/v#{version}/Lore-v#{version}-aarch64-apple-darwin.zip"
  name "Lore"
  desc "Personal knowledge management desktop app"
  homepage "https://github.com/AoJ/lore"

  depends_on arch: :arm64
  depends_on macos: :big_sur

  app "Lore.app"

  caveats <<~EOS
    Lore.app is Developer ID signed + notarized, so it launches without a
    Gatekeeper prompt. The database defaults to
    ~/Library/Application Support/lore/lore.db (override with LORE_DB; note a
    Dock/Finder-launched app does not inherit your shell environment).
  EOS
end
