# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/release.yml on each tagged release.
# Source template: tools/homebrew/lore.formula.rb in AoJ/lore. Do not hand-edit
# in the tap — edit the template instead.
require "download_strategy"

# Download private release assets using a lore-specific token
# (HOMEBREW_LORE_GITHUB_TOKEN) rather than the global HOMEBREW_GITHUB_API_TOKEN.
# This lets a token for a different GitHub account stay in the global var without
# colliding with the token that can read AoJ/lore.
unless defined?(GitHubPrivateLoreDownloadStrategy)
  class GitHubPrivateLoreDownloadStrategy < GitHubPrivateRepositoryReleaseDownloadStrategy
    def set_github_token
      @github_token = ENV.fetch("HOMEBREW_LORE_GITHUB_TOKEN", nil)
      if @github_token.nil? || @github_token.empty?
        raise CurlDownloadStrategyError, "HOMEBREW_LORE_GITHUB_TOKEN is required to install lore"
      end
    end
  end
end

class Lore < Formula
  desc "Personal knowledge management tool (headless: lore, lore-serve, lore-worker)"
  homepage "https://github.com/AoJ/lore"
  version "@@VERSION@@"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-aarch64-apple-darwin.tar.gz",
          using: GitHubPrivateLoreDownloadStrategy
      sha256 "@@SHA_MACOS_ARM@@"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-x86_64-unknown-linux-gnu.tar.gz",
          using: GitHubPrivateLoreDownloadStrategy
      sha256 "@@SHA_LINUX_X86@@"
    end
    on_arm do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-aarch64-unknown-linux-gnu.tar.gz",
          using: GitHubPrivateLoreDownloadStrategy
      sha256 "@@SHA_LINUX_ARM@@"
    end
  end

  def install
    bin.install "lore", "lore-serve", "lore-worker"
  end

  def caveats
    <<~EOS
      A token with read access to the private AoJ/lore repo is required for
      install and upgrade. Put it in your shell rc (separate from any global
      HOMEBREW_GITHUB_API_TOKEN):
        export HOMEBREW_LORE_GITHUB_TOKEN=ghp_...

      The database defaults to:
        ~/Library/Application Support/lore/lore.db   (macOS)
        $XDG_DATA_HOME/lore/lore.db                  (Linux)
      Override the location with LORE_DB:
        export LORE_DB="$HOME/lore.db"
    EOS
  end

  test do
    assert_match "lore", shell_output("#{bin}/lore --help 2>&1", 2)
  end
end
