# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/release.yml on each tagged release.
# Source template: tools/homebrew/lore.cask.rb in AoJ/lore. Do not hand-edit
# in the tap — edit the template instead.
require "download_strategy"

# Why a custom strategy (unlike the formula, which uses the built-in one):
#   1. GitHubPrivateRepositoryReleaseDownloadStrategy is NOT defined in cask
#      context — referencing it there raises "uninitialized constant".
#   2. Newer Homebrew scrubs token-like env vars during cask `instance_eval`, so
#      the token can't be read at load time (in `url`/headers) — only at fetch.
# So: a minimal CurlDownloadStrategy that, at download time, reads
# HOMEBREW_GITHUB_API_TOKEN and fetches the asset via the GitHub API asset
# endpoint (numeric id templated in at release time). The token goes in the URL
# userinfo, NOT an Authorization header — Homebrew/curl forwards that header to
# the S3 redirect target and breaks the download (Homebrew/brew#15244).
unless defined?(GitHubPrivateLoreDownloadStrategy)
  class GitHubPrivateLoreDownloadStrategy < CurlDownloadStrategy
    def download_url
      token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      if token.nil? || token.empty?
        raise CurlDownloadStrategyError,
              "HOMEBREW_GITHUB_API_TOKEN with read access to AoJ/lore is required"
      end
      @url.sub(%r{\Ahttps://}, "https://#{token}@")
    end

    # Resolve via the authenticated URL (the bare API asset URL 404s without the
    # token), and force a .zip basename so Homebrew knows to unpack it (the API
    # asset path ends in a numeric id, not a filename).
    def resolve_url_basename_time_file_size(_url, timeout: nil)
      super(download_url, timeout: timeout)
    end

    def resolved_basename
      "lore.zip"
    end

    private

    def _fetch(url:, resolved_url:, timeout:)
      curl_download download_url, "--header", "Accept: application/octet-stream", to: temporary_path
    end
  end
end

cask "lore" do
  version "@@VERSION@@"
  sha256 "@@SHA_APP@@"

  url "https://api.github.com/repos/AoJ/lore/releases/assets/@@CASK_ASSET_ID@@",
      using: GitHubPrivateLoreDownloadStrategy
  name "Lore"
  desc "Personal knowledge management desktop app"
  homepage "https://github.com/AoJ/lore"

  depends_on arch: :arm64
  depends_on macos: ">= :big_sur"

  app "Lore.app"

  caveats <<~EOS
    Set HOMEBREW_GITHUB_API_TOKEN to a token with read access to AoJ/lore
    before install/upgrade:
      export HOMEBREW_GITHUB_API_TOKEN=github_pat_...

    Lore.app is ad-hoc signed but NOT notarized, so a plain install gets the
    macOS "Apple could not verify" Gatekeeper block. Install without quarantine:
      brew install --cask --no-quarantine lore
    Or make it the default for all casks (in your shell rc):
      export HOMEBREW_CASK_OPTS=--no-quarantine

    The database defaults to ~/Library/Application Support/lore/lore.db.
    Note: when launched from the Dock/Finder the app does not inherit your
    shell environment, so LORE_DB set in a shell rc will not apply there —
    the default location is used.
  EOS
end
