# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/release.yml on each tagged release.
# Source template: tools/homebrew/lore.formula.rb in AoJ/lore. Do not hand-edit
# in the tap — edit the template instead.
require "download_strategy"

class Lore < Formula
  desc "Personal knowledge management tool (headless: lore, lore-serve, lore-worker)"
  homepage "https://github.com/AoJ/lore"
  version "@@VERSION@@"
  license "MIT"

  # Private release assets — Homebrew's built-in strategy authenticates with
  # HOMEBREW_GITHUB_API_TOKEN (must have read access to AoJ/lore). The desktop
  # GUI ships as a separate cask (notarized Lore.app), not here.
  on_macos do
    on_arm do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-aarch64-apple-darwin.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "@@SHA_MACOS_ARM@@"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-x86_64-unknown-linux-gnu.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "@@SHA_LINUX_X86@@"
    end
    on_arm do
      url "https://github.com/AoJ/lore/releases/download/v#{version}/lore-v#{version}-aarch64-unknown-linux-gnu.tar.gz",
          using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "@@SHA_LINUX_ARM@@"
    end
  end

  def install
    bin.install "lore", "lore-serve", "lore-worker"
  end

  def caveats
    <<~EOS
      Set HOMEBREW_GITHUB_API_TOKEN to a token with read access to AoJ/lore
      before install/upgrade:
        export HOMEBREW_GITHUB_API_TOKEN=github_pat_...

      The database defaults to:
        ~/Library/Application Support/lore/lore.db   (macOS)
        $XDG_DATA_HOME/lore/lore.db                  (Linux)
      Override the location with LORE_DB:
        export LORE_DB="$HOME/lore.db"

      The desktop GUI ships separately:  brew install --cask lore
    EOS
  end

  test do
    assert_match "lore", shell_output("#{bin}/lore --help 2>&1", 2)
  end
end
