# typed: false
# frozen_string_literal: true

# Auto-generated by .github/workflows/release.yml on each tagged release.
# Source template: tools/homebrew/lore.cask.rb in AoJ/lore. Do not hand-edit
# in the tap — edit the template instead.
require "download_strategy"

# See the formula for why this exists: download private release assets with the
# lore-specific HOMEBREW_LORE_GITHUB_TOKEN instead of the global token.
unless defined?(GitHubPrivateLoreDownloadStrategy)
  class GitHubPrivateLoreDownloadStrategy < GitHubPrivateRepositoryReleaseDownloadStrategy
    def set_github_token
      @github_token = ENV.fetch("HOMEBREW_LORE_GITHUB_TOKEN", nil)
      if @github_token.nil? || @github_token.empty?
        raise CurlDownloadStrategyError, "HOMEBREW_LORE_GITHUB_TOKEN is required to install lore"
      end
    end
  end
end

cask "lore" do
  version "@@VERSION@@"
  sha256 "@@SHA_APP@@"

  url "https://github.com/AoJ/lore/releases/download/v#{version}/Lore-v#{version}-aarch64-apple-darwin.zip",
      using: GitHubPrivateLoreDownloadStrategy
  name "Lore"
  desc "Personal knowledge management desktop app"
  homepage "https://github.com/AoJ/lore"

  depends_on arch: :arm64
  depends_on macos: ">= :big_sur"

  app "Lore.app"

  caveats <<~EOS
    A token with read access to the private AoJ/lore repo is required for
    install and upgrade. Put it in your shell rc (separate from any global
    HOMEBREW_GITHUB_API_TOKEN):
      export HOMEBREW_LORE_GITHUB_TOKEN=ghp_...

    The database defaults to ~/Library/Application Support/lore/lore.db.
    Note: when launched from the Dock/Finder the app does not inherit your
    shell environment, so LORE_DB set in a shell rc will not apply there —
    the default location is used.
  EOS
end
